*&---------------------------------------------------------------------*
*& Report ZAI_ECATT_CREATOR
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZAI_ECATT_CREATOR.
TABLES: SSCRFIELDS,
        /SMB/S_BBM_UI,
        /SMB/S_SIC_UI.

INCLUDE:<ICON>,
        ZABAP_AI_I0001,
        ZTYPES_UTILITY,
        ZCOUNTRY_UTILITY,
        ZIBAN_GERERATOR_UTILITY,
        ZAI_MASTERDATA_CREATOR.

SELECTION-SCREEN:
FUNCTION KEY 1,
FUNCTION KEY 2,
FUNCTION KEY 3.

DATA: GO_SCREEN_1000 TYPE REF TO LCL_SCREEN_1000.

PARAMETERS: P_ECAT  TYPE ETOBJ_NAME OBLIGATORY.

SELECT-OPTIONS: S_CCSI1 FOR /SMB/S_SIC_UI-SIC_ID NO INTERVALS NO-EXTENSION.
SELECT-OPTIONS: S_CCBB1 FOR /SMB/S_BBM_UI-BBM_ID NO INTERVALS OBLIGATORY.
PARAMETERS: P_TTTP1 TYPE T005-LAND1 OBLIGATORY MEMORY ID LD1.
PARAMETERS: P_TTNUM TYPE I DEFAULT 3 OBLIGATORY.
" SELECTION-SCREEN ULINE.
SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK1.
  SELECTION-SCREEN : BEGIN OF LINE,
  PUSHBUTTON 01(20) T_LOADBP USER-COMMAND BPLOAD,
  PUSHBUTTON 40(20) T_CREATE USER-COMMAND BPCREATE,
  PUSHBUTTON 80(20) T_CHECK  USER-COMMAND BPCHECK,
  END OF LINE.

  PARAMETERS: P_FORAMT TYPE C DEFAULT ABAP_TRUE NO-DISPLAY.
SELECTION-SCREEN END OF BLOCK BLOCK1.

INITIALIZATION.
  DATA : L_SEL_BUTTON TYPE SMP_DYNTXT.
  DEFINE FUNCTXT.
    L_SEL_BUTTON-ICON_ID = &2.
    L_SEL_BUTTON-ICON_TEXT = &3.
    SSCRFIELDS-FUNCTXT_&1 = L_SEL_BUTTON.
  END-OF-DEFINITION.

  LCL_SETTING=>READ_SETTING( ).

  FUNCTXT 01 ICON_WD_TEXT_EDIT 'Prompt Viewer'.
  FUNCTXT 02 ICON_DISPO_LEVEL 'Distinguish categories'.
*  FUNCTXT 03 ICON_SYSTEM_SAVE 'Save setting...'.

  T_LOADBP = 'Load template'.
  T_CREATE = 'Run (With AI)'.
  T_CHECK = 'Check (No AI)'.

  DATA: LT_VALUES         TYPE VRM_VALUES,
        LS_VALUE          LIKE LINE OF LT_VALUES,
        GO_COUNTRY_VIEWER TYPE REF TO CL_COUNTRY_VIEWER.

  CREATE OBJECT GO_COUNTRY_VIEWER EXPORTING I_DEUS = ABAP_TRUE.

  GO_SCREEN_1000 = NEW LCL_SCREEN_1000( ).
  GO_SCREEN_1000->INIT_CNTL( ).

AT SELECTION-SCREEN.
  IF P_TTNUM <= 0 AND P_TTNUM > 10.
    MESSAGE E001(00) WITH 'The entries of AI create between 1 to 10.'.
  ENDIF.

  CASE SSCRFIELDS-UCOMM.
    WHEN 'FC01'.
      GO_SCREEN_1000->PROMPT_EDITOR( ).
    WHEN 'FC02'.
      GO_SCREEN_1000->DISTINGUISH_CATEGORIES( ).
    WHEN 'BPCREATE'.
      GO_SCREEN_1000->CREATE_VFILE(
        I_TARCOUNTRY  = P_TTTP1
        I_FORMAT      = P_FORAMT
        I_NUMCREATE   = P_TTNUM
        ING_SIR_SI_ID = S_CCSI1[]
      ).
    WHEN 'BPCHECK'.
      GO_SCREEN_1000->CHECK_VFILE(
        I_TARCOUNTRY  = P_TTTP1
        I_FORMAT      = P_FORAMT
        I_NUMCREATE   = P_TTNUM
        ING_SIR_SI_ID = S_CCSI1[]
      ).
    WHEN 'BPLOAD'.
      GO_COUNTRY_VIEWER->GET_CONTRY_LIST(
        IMPORTING
          CONTRY_LIST = DATA(LT_CONTRY_LIST)
      ).
      GO_SCREEN_1000->LOAD_ECATT_DEFINE( I_ECATT = P_ECAT ).
      GO_SCREEN_1000->FILL_ECATT_DEFINE( I_ECATT = P_ECAT ).

      SELECT BBM_ID FROM /SMB/I_BB_ATTRIBUTES INTO TABLE @DATA(LT_BB_ATTR)
        WHERE BBM_ID IN @S_CCBB1.
      GO_SCREEN_1000->LOAD_P4_VFILE( I_ECATT  = P_ECAT
                                     IT_LAND1 = VALUE #( FOR C IN LT_CONTRY_LIST ( C-LAND1 ) )
                                     IT_BBMID = VALUE #( FOR L IN LT_BB_ATTR     ( L-BBM_ID ) )
                                     ).
      GO_SCREEN_1000->FILL_P4_VFILE( I_ECATT = P_ECAT ).
    WHEN OTHERS.
  ENDCASE.

  GO_SCREEN_1000->SAVE_SETTING( ).
