*&---------------------------------------------------------------------*
*& Report ZAI_ECATT_MASTERDATA_CREATOR
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZAI_ECATT_MASTERDATA_CREATOR.
TABLES: SSCRFIELDS,
        /SMB/S_BBM_UI,
        /SMB/S_SIC_UI.

INCLUDE:<ICON>,
        ZABAP_AI_I0001,
        ZTYPES_UTILITY,
        ZCOUNTRY_UTILITY,
        ZIBAN_GERERATOR_UTILITY,
        ZAI_MASTERDATA_CREATOR.

SELECTION-SCREEN:
FUNCTION KEY 1,
FUNCTION KEY 2,
FUNCTION KEY 3.

TYPES: TNG_BBID TYPE RANGE OF /SMB/S_BBM_UI-BBM_ID.

DATA: GO_SCREEN_1000 TYPE REF TO LCL_SCREEN_1000.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK1.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(20) T_R_BP FOR FIELD R_BP.
    PARAMETERS R_BP RADIOBUTTON GROUP TAD1 DEFAULT 'X' USER-COMMAND RTYPE.
    SELECTION-SCREEN POSITION 20.
    SELECTION-SCREEN COMMENT 31(10) T_R_MM FOR FIELD R_MM.
    PARAMETERS R_MM RADIOBUTTON GROUP TAD1.
  SELECTION-SCREEN END OF LINE.

  PARAMETERS: P_ECAT  TYPE ETOBJ_NAME AS LISTBOX VISIBLE LENGTH 30.

SELECTION-SCREEN END OF BLOCK BLOCK1.

SELECT-OPTIONS: S_CCSI1 FOR /SMB/S_SIC_UI-SIC_ID NO INTERVALS NO-EXTENSION.
SELECT-OPTIONS: S_CCBB1 FOR /SMB/S_BBM_UI-BBM_ID NO INTERVALS.
PARAMETERS: P_TTTP1 TYPE T005-LAND1 MEMORY ID LD1.
PARAMETERS: P_TTNUM TYPE I DEFAULT 3 OBLIGATORY.
" SELECTION-SCREEN ULINE.
SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK2.
  SELECTION-SCREEN : BEGIN OF LINE,
  PUSHBUTTON 01(20) T_LOADBP USER-COMMAND BPLOAD,
  PUSHBUTTON 40(20) T_CREATE USER-COMMAND BPCREATE,
  PUSHBUTTON 80(20) T_CHECK  USER-COMMAND BPCHECK,
  END OF LINE.

  PARAMETERS: P_FORAMT TYPE C DEFAULT ABAP_TRUE NO-DISPLAY.
SELECTION-SCREEN END OF BLOCK BLOCK2.

INITIALIZATION.
  DATA : L_SEL_BUTTON TYPE SMP_DYNTXT.
  DEFINE FUNCTXT.
    L_SEL_BUTTON-ICON_ID = &2.
    L_SEL_BUTTON-ICON_TEXT = &3.
    SSCRFIELDS-FUNCTXT_&1 = L_SEL_BUTTON.
  END-OF-DEFINITION.

  LCL_SETTING=>READ_SETTING( ).

  FUNCTXT 01 ICON_WD_TEXT_EDIT 'Prompt Viewer'.
  FUNCTXT 02 ICON_DISPO_LEVEL 'Distinguish categories'.
*  FUNCTXT 03 ICON_SYSTEM_SAVE 'Save setting...'.

  T_R_MM = 'Material'.
  T_R_BP = 'Buiness Partner'.

  T_LOADBP = 'Load template'.
  T_CREATE = 'Create (With AI)'.
  T_CHECK = 'Check (No AI)'.



*  APPEND LINES OF VALUE TNG_BBID( ( LOW = 'JA2' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = '1UP' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '1UR' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '1VJ' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '2IS' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = '3AN' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '3AO' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '3C8' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '3IS' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = '3JI' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '3JY' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '47A' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '4BO' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = '4CH' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '4OK' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '4V8' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '4YU' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = '5EI' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '5IL' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '5JC' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '5NF' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = '5QB' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '5V3' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '65S' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '6FD' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = '6FE' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '6OZ' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '72E' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '7OM' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = '7OV' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '7QI' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = '7QK' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'BL2' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = 'BLS' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'BLU' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'BN5' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'BN6' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = 'BN8' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'BN9' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'BNB' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'BRC' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = 'BRS' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'J16' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'J88' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'JA2' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*( LOW = 'PS4' HIGH = '' OPTION = 'EQ' SIGN = 'I' ) ( LOW = 'ROS' HIGH = '' OPTION = 'EQ' SIGN = 'I' )
*  ) TO S_CCBB1.


  DATA GO_COUNTRY_VIEWER TYPE REF TO CL_COUNTRY_VIEWER.
  CREATE OBJECT GO_COUNTRY_VIEWER EXPORTING I_DEUS = ABAP_TRUE.

  GO_SCREEN_1000 = NEW LCL_SCREEN_1000( ).
  GO_SCREEN_1000->LOAD_ECATT_DEFINE( ).

*  LC_BP_CREATOR_OF_AI->LOAD_BP_ECATT_DEFINE( I_ECATT = P_ECAT ).
*  LC_BP_CREATOR_OF_AI->FILL_BP_ECATT_DEFINE( I_ECATT = P_ECAT ).

*AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_ECAT.
*  LC_BP_CREATOR_OF_AI->LOAD_BP_ECATT_DEFINE( I_ECATT = P_ECAT ).
*  LC_BP_CREATOR_OF_AI->FILL_BP_ECATT_DEFINE( I_ECATT = P_ECAT ).
*  LC_BP_CREATOR_OF_AI->LOAD_P4_VFILE( I_ECATT  = P_ECAT
*                                      IT_LAND1 = VALUE #( ( P_CCTP1 ) ( P_CCTP2 ) ( P_TTTP1 ) )
*                                      IT_BBMID = VALUE #( ( P_CCBB1 ) )
*                                      ).
*  LC_BP_CREATOR_OF_AI->FILL_P4_VFILE( I_ECATT = P_ECAT ).
*  PERFORM INIT_SELECTION_SCREEN.

AT SELECTION-SCREEN OUTPUT.
  PERFORM INIT_SELECTION_SCREEN.


AT SELECTION-SCREEN.

  CASE SSCRFIELDS-UCOMM.
    WHEN 'FC01'.
      GO_SCREEN_1000->PROMPT_EDITOR( ).
    WHEN 'FC02'.
      GO_SCREEN_1000->DISTINGUISH_CATEGORIES( ).
*    WHEN 'FC03'.
*      GO_SCREEN_1000->SAVE_OPTION_FIELDS( ).
    WHEN 'BPCREATE'.
      PERFORM CHECK_INPUT.
      GO_SCREEN_1000->CREATE_VFILE(
        I_TARCOUNTRY  = P_TTTP1
        I_FORMAT      = P_FORAMT
        I_NUMCREATE   = P_TTNUM
        ING_SIR_SI_ID = S_CCSI1[]
      ).
    WHEN 'BPCHECK'.
      PERFORM CHECK_INPUT.
      GO_SCREEN_1000->CHECK_VFILE(
        I_TARCOUNTRY  = P_TTTP1
        I_FORMAT      = P_FORAMT
        I_NUMCREATE   = P_TTNUM
        ING_SIR_SI_ID = S_CCSI1[]
      ).
    WHEN 'BPLOAD'.
      PERFORM CHECK_INPUT.
      GO_COUNTRY_VIEWER->GET_CONTRY_LIST(
        IMPORTING
          CONTRY_LIST = DATA(LT_CONTRY_LIST)
      ).
      GO_SCREEN_1000->LOAD_ECATT_DEFINE( I_ECATT = P_ECAT ).
      GO_SCREEN_1000->FILL_ECATT_DEFINE( I_ECATT = P_ECAT ).

      SELECT BBM_ID FROM /SMB/I_BB_ATTRIBUTES INTO TABLE @DATA(LT_BB_ATTR)
        WHERE BBM_ID IN @S_CCBB1.
      GO_SCREEN_1000->LOAD_P4_VFILE( I_ECATT  = P_ECAT
                                     IT_LAND1 = VALUE #( FOR C IN LT_CONTRY_LIST ( C-LAND1 ) )
                                     IT_BBMID = VALUE #( FOR L IN LT_BB_ATTR     ( L-BBM_ID ) )
                                     ).
      GO_SCREEN_1000->FILL_P4_VFILE( I_ECATT = P_ECAT ).
    WHEN OTHERS.
  ENDCASE.

  GO_SCREEN_1000->SAVE_SETTING( ).

FORM CHECK_INPUT.
  IF P_TTNUM <= 0 AND P_TTNUM > 10.
    MESSAGE E001(00) WITH 'The entries of AI create between 1 to 10.'.
  ENDIF.

  IF P_ECAT IS INITIAL.
    MESSAGE E001(00) WITH 'Choice an eCATT.'.
  ENDIF.

  IF S_CCBB1[] IS INITIAL.
    MESSAGE E001(00) WITH 'Input BB name.'.
  ENDIF.

  IF P_TTTP1 IS INITIAL.
    MESSAGE E001(00) WITH 'Input country ID.'.
  ENDIF.


  IF /SMB/CL_CHECK_USER_SETTINGS=>IS_DECIMAL_FORMAT_CORRECT( ) EQ ABAP_FALSE.
    MESSAGE E088(/SMB/SBA1).
  ENDIF.

  IF /SMB/CL_CHECK_USER_SETTINGS=>IS_DATE_FORMAT_CORRECT( ) EQ ABAP_FALSE.
    MESSAGE E087(/SMB/SBA1).
  ENDIF.

  CASE ABAP_TRUE.
    WHEN R_MM.
      LCL_SETTING=>MODIFY_SETTING( I_SETTING_ID = 'MM_P_ECATT' I_SETTING_VALUE = CONV STRING( P_ECAT ) ).
    WHEN R_BP.
      LCL_SETTING=>MODIFY_SETTING( I_SETTING_ID = 'BP_P_ECATT' I_SETTING_VALUE = CONV STRING( P_ECAT ) ).
  ENDCASE.

ENDFORM.

FORM INIT_SELECTION_SCREEN.
  DATA: LT_VALUES TYPE VRM_VALUES,
        LS_VALUE  LIKE LINE OF LT_VALUES.

  GO_SCREEN_1000->GET_ECATT_DEFINES(
    IMPORTING
      ET_ECATT_DEFINES = DATA(LT_ECATT_DEFINES)
  ).
  SORT LT_ECATT_DEFINES BY ECATT ASCENDING.

  CASE ABAP_TRUE.
    WHEN R_MM.
      DELETE LT_ECATT_DEFINES WHERE CLASS <> LCL_SCREEN_1000=>MC_MM_ABAP_CLASS.
      P_ECAT = VALUE #( LCL_SETTING=>MT_SETTING[ SETTING_ID = 'MM_P_ECATT' ]-SETTING_VALUE DEFAULT '/SMB99/MARA_E1_O001' ). " Control Extension.
*      P_ECAT = '/SMB99/MARA_E1_O001'.
    WHEN R_BP.
      DELETE LT_ECATT_DEFINES WHERE CLASS <> LCL_SCREEN_1000=>MC_BP_ABAP_CLASS_CUSTOMER AND
                                    CLASS <> LCL_SCREEN_1000=>MC_BP_ABAP_CLASS_VERNDOR.
      P_ECAT = VALUE #( LCL_SETTING=>MT_SETTING[ SETTING_ID = 'BP_P_ECATT' ]-SETTING_VALUE DEFAULT '/SMB99/BP_GEN_O001' ). " Control Extension.

*      P_ECAT = '/SMB99/BP_GEN_O001'.
    WHEN OTHERS.
  ENDCASE.
  READ TABLE LT_ECATT_DEFINES TRANSPORTING NO FIELDS WITH KEY ECATT = P_ECAT.
  IF SY-SUBRC <> 0.
    CLEAR P_ECAT.
    IF LT_ECATT_DEFINES IS NOT INITIAL.
      P_ECAT = LT_ECATT_DEFINES[ 1 ]-ECATT.
    ENDIF.
  ENDIF.

  LOOP AT LT_ECATT_DEFINES INTO DATA(LS_ECATT_DEFINES).
    " LS_VALUE-KEY = SY-TABIX.
    " LS_VALUE-TEXT = LS_ECATT_DEFINES-ECATT.
    LS_VALUE-KEY = LS_ECATT_DEFINES-ECATT.
    APPEND LS_VALUE TO LT_VALUES.
  ENDLOOP.

  CALL FUNCTION 'VRM_DELETE_VALUES'
    EXPORTING
      ID           = 'P_ECAT'
*     ID_CONTAINS_PROGNAME = ID_CONTAINS_PROGNAME " ID already contains the program; details in the documentation
    EXCEPTIONS
      ID_NOT_FOUND = 1.                    " The value set (ID) does not exist

  CALL FUNCTION 'VRM_SET_VALUES'
    EXPORTING
      ID     = 'P_ECAT'
      VALUES = LT_VALUES.

  GO_SCREEN_1000->INIT_CNTL( ).


ENDFORM.
